repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: /Users/christopherfleck/Projects/Context/venv/bin/pyright
        language: system
        types: [python]
